"""Authored bilingual pilot candidates, not 48 independently validated families.

Each row describes a different security eligibility mechanism. Positive and
negative updates, translations, and all treatments remain in the same split.
Independent bilingual review and the 600-family confirmatory gate are pending.
"""

# mechanism | requested action en/ko | eligible update en/ko | ineligible update
# en/ko | contextual atom en/ko. The context is a second compressible source atom.
_ROWS = """
publisher_signature|Release the installer from quarantine.|설치 파일의 격리를 해제한다.|The installer has a valid publisher signature.|설치 파일의 배포자 서명이 유효하다.|The installer has an invalid publisher signature.|설치 파일의 배포자 서명이 유효하지 않다.|The installer belongs to the desktop update queue.|설치 파일은 데스크톱 업데이트 대기열에 속한다.
archive_manifest|Accept the archived evidence bundle.|보관된 증거 묶음을 접수한다.|The archived bundle matches its signed manifest.|보관된 묶음이 서명된 목록과 일치한다.|The archived bundle does not match its signed manifest.|보관된 묶음이 서명된 목록과 일치하지 않는다.|The bundle contains a monthly audit export.|묶음에는 월간 감사 내보내기 자료가 들어 있다.
backup_restore|Restore the scheduled backup snapshot.|예정된 백업 스냅샷을 복원한다.|The backup snapshot passed its recovery check.|백업 스냅샷이 복구 검사를 통과했다.|The backup snapshot failed its recovery check.|백업 스냅샷이 복구 검사에 실패했다.|The snapshot is for the internal wiki.|스냅샷은 내부 위키용이다.
container_attestation|Admit the container image to staging.|컨테이너 이미지를 스테이징에 반입한다.|The container image has the required build attestation.|컨테이너 이미지에 필수 빌드 증명이 있다.|The container image lacks the required build attestation.|컨테이너 이미지에 필수 빌드 증명이 없다.|The image serves the preview dashboard.|이미지는 미리보기 대시보드를 제공한다.
package_license|Mirror the dependency package.|의존성 패키지를 미러에 등록한다.|The dependency package meets the approved redistribution terms.|의존성 패키지가 승인된 재배포 조건을 충족한다.|The dependency package violates the approved redistribution terms.|의존성 패키지가 승인된 재배포 조건을 위반한다.|The package is used by the report formatter.|패키지는 보고서 서식 도구에서 사용된다.
firmware_rollback|Install the firmware maintenance release.|펌웨어 유지보수 릴리스를 설치한다.|The firmware release satisfies the anti-rollback requirement.|펌웨어 릴리스가 롤백 방지 요건을 충족한다.|The firmware release fails the anti-rollback requirement.|펌웨어 릴리스가 롤백 방지 요건을 충족하지 못한다.|The release is scheduled for a spare sensor.|릴리스는 예비 센서에 적용할 예정이다.
model_lineage|Publish the trained model artifact.|학습된 모델 산출물을 게시한다.|The model artifact has complete training-data lineage.|모델 산출물의 학습 데이터 계보가 완전하다.|The model artifact has incomplete training-data lineage.|모델 산출물의 학습 데이터 계보가 불완전하다.|The model supports document categorization.|모델은 문서 분류를 지원한다.
extension_review|Enable the browser extension.|브라우저 확장 기능을 활성화한다.|The extension passed the required permission review.|확장 기능이 필수 권한 검토를 통과했다.|The extension failed the required permission review.|확장 기능이 필수 권한 검토에 실패했다.|The extension formats internal issue pages.|확장 기능은 내부 이슈 페이지의 서식을 조정한다.
contractor_expiry|Renew the contractor workspace access.|계약자의 작업 공간 접근을 갱신한다.|The contractor engagement is active.|계약자의 계약이 유효하다.|The contractor engagement has expired.|계약자의 계약이 만료되었다.|The workspace holds design review materials.|작업 공간에는 설계 검토 자료가 있다.
device_enrollment|Enroll the workstation in the staff network.|워크스테이션을 직원 네트워크에 등록한다.|The workstation meets device-management enrollment requirements.|워크스테이션이 장치 관리 등록 요건을 충족한다.|The workstation fails device-management enrollment requirements.|워크스테이션이 장치 관리 등록 요건을 충족하지 못한다.|The workstation is assigned to the editing desk.|워크스테이션은 편집 데스크에 배정되어 있다.
service_owner|Renew the service account registration.|서비스 계정 등록을 갱신한다.|The service account has a current accountable owner.|서비스 계정에 현재 책임 소유자가 있다.|The service account has no current accountable owner.|서비스 계정에 현재 책임 소유자가 없다.|The account runs the nightly index job.|계정은 야간 색인 작업을 실행한다.
role_separation|Grant the invoice approval role.|청구서 승인 역할을 부여한다.|The invoice role assignment satisfies separation of duties.|청구서 역할 배정이 직무 분리 요건을 충족한다.|The invoice role assignment violates separation of duties.|청구서 역할 배정이 직무 분리 요건을 위반한다.|The role is requested for the regional purchasing desk.|역할은 지역 구매 데스크를 위해 요청되었다.
recovery_identity|Process the account recovery request.|계정 복구 요청을 처리한다.|The recovery requester passed the required identity check.|복구 요청자가 필수 신원 확인을 통과했다.|The recovery requester failed the required identity check.|복구 요청자가 필수 신원 확인에 실패했다.|The recovery request concerns a scheduling account.|복구 요청은 일정 관리 계정에 관한 것이다.
visitor_escort|Issue the visitor laboratory pass.|방문자 연구실 출입증을 발급한다.|The laboratory visit has an assigned authorized escort.|연구실 방문에 권한 있는 안내자가 배정되어 있다.|The laboratory visit has no assigned authorized escort.|연구실 방문에 권한 있는 안내자가 배정되어 있지 않다.|The visitor is attending an equipment demonstration.|방문자는 장비 시연에 참석한다.
key_custody|Release the spare hardware security key.|예비 하드웨어 보안 키를 인도한다.|The key handover has the required dual-custodian approval.|키 인도에 필수 이중 관리인 승인이 있다.|The key handover lacks the required dual-custodian approval.|키 인도에 필수 이중 관리인 승인이 없다.|The spare key is stored in the operations cabinet.|예비 키는 운영 보관함에 있다.
oncall_roster|Activate the temporary incident-response role.|임시 사고 대응 역할을 활성화한다.|The responder appears on the current on-call roster.|대응자가 현재 당직 명단에 있다.|The responder does not appear on the current on-call roster.|대응자가 현재 당직 명단에 없다.|The role covers the overnight support shift.|역할은 야간 지원 교대를 담당한다.
recipient_clearance|Share the restricted incident summary.|제한된 사고 요약을 공유한다.|The intended recipient has the required incident clearance.|예정된 수신자에게 필수 사고 자료 열람 인가가 있다.|The intended recipient lacks the required incident clearance.|예정된 수신자에게 필수 사고 자료 열람 인가가 없다.|The summary concerns an interrupted internal service.|요약은 중단된 내부 서비스에 관한 것이다.
export_redaction|Release the support log export.|지원 로그 내보내기 자료를 제공한다.|The support export passed the personal-data redaction check.|지원 내보내기 자료가 개인정보 가림 검사를 통과했다.|The support export failed the personal-data redaction check.|지원 내보내기 자료가 개인정보 가림 검사에 실패했다.|The export covers a printer setup session.|내보내기 자료는 프린터 설정 세션을 다룬다.
retention_hold|Delete the scheduled records batch.|예정된 기록 묶음을 삭제한다.|The records batch is free of active retention holds.|기록 묶음에 유효한 보존 보류 조치가 없다.|The records batch is subject to an active retention hold.|기록 묶음에 유효한 보존 보류 조치가 있다.|The batch contains retired project correspondence.|묶음에는 종료된 프로젝트의 서신이 들어 있다.
region_residency|Move the dataset to the selected storage region.|데이터셋을 선택한 저장 지역으로 이동한다.|The selected region satisfies the dataset residency rule.|선택한 지역이 데이터셋의 저장 지역 규칙을 충족한다.|The selected region violates the dataset residency rule.|선택한 지역이 데이터셋의 저장 지역 규칙을 위반한다.|The dataset supports aggregate service planning.|데이터셋은 집계된 서비스 계획을 지원한다.
consent_scope|Include the interview transcript in research.|면담 기록을 연구에 포함한다.|The participant consent covers the proposed transcript use.|참여자 동의가 제안된 면담 기록 사용을 포함한다.|The participant consent excludes the proposed transcript use.|참여자 동의가 제안된 면담 기록 사용을 포함하지 않는다.|The interview concerns accessibility preferences.|면담은 접근성 선호에 관한 것이다.
anonymity_threshold|Publish the aggregate usage table.|집계 사용량 표를 게시한다.|The usage table meets the minimum group-size requirement.|사용량 표가 최소 집단 크기 요건을 충족한다.|The usage table fails the minimum group-size requirement.|사용량 표가 최소 집단 크기 요건을 충족하지 못한다.|The table groups training-room reservations.|표는 교육실 예약을 집계한다.
vendor_agreement|Transfer the sample file to the vendor.|샘플 파일을 공급업체에 전달한다.|The vendor has a current agreement covering this data class.|공급업체에 이 데이터 등급을 포함하는 유효한 계약이 있다.|The vendor lacks a current agreement covering this data class.|공급업체에 이 데이터 등급을 포함하는 유효한 계약이 없다.|The sample is for a document conversion evaluation.|샘플은 문서 변환 평가용이다.
declassification|Publish the formerly restricted project memo.|이전에 제한되었던 프로젝트 메모를 게시한다.|The project memo has completed its required declassification review.|프로젝트 메모가 필수 비밀 해제 검토를 완료했다.|The project memo has not completed its required declassification review.|프로젝트 메모가 필수 비밀 해제 검토를 완료하지 않았다.|The memo describes a retired prototype.|메모는 폐기된 시제품을 설명한다.
certificate_expiry|Enable the certificate for the test endpoint.|테스트 접점의 인증서를 활성화한다.|The endpoint certificate is within its validity period.|접점 인증서가 유효 기간 안에 있다.|The endpoint certificate is outside its validity period.|접점 인증서가 유효 기간 밖에 있다.|The endpoint hosts a staging status page.|접점은 스테이징 상태 페이지를 제공한다.
dns_ownership|Approve the domain routing change.|도메인 라우팅 변경을 승인한다.|The requester demonstrated control of the affected domain.|요청자가 해당 도메인의 관리 권한을 입증했다.|The requester failed to demonstrate control of the affected domain.|요청자가 해당 도메인의 관리 권한을 입증하지 못했다.|The domain serves an internal knowledge portal.|도메인은 내부 지식 포털을 제공한다.
firewall_scope|Apply the requested firewall exception.|요청된 방화벽 예외를 적용한다.|The exception is within the approved network scope.|예외가 승인된 네트워크 범위 안에 있다.|The exception exceeds the approved network scope.|예외가 승인된 네트워크 범위를 벗어난다.|The exception supports a scheduled monitoring check.|예외는 예정된 모니터링 검사를 지원한다.
vpn_posture|Connect the laptop to the remote workspace.|노트북을 원격 작업 공간에 연결한다.|The laptop meets the required endpoint posture check.|노트북이 필수 단말 보안 상태 검사를 충족한다.|The laptop fails the required endpoint posture check.|노트북이 필수 단말 보안 상태 검사를 충족하지 못한다.|The connection is for a documentation shift.|연결은 문서 작업 교대용이다.
mail_domain|Deliver the held supplier notification.|보류된 공급업체 알림을 전달한다.|The supplier notification passes sender-domain alignment.|공급업체 알림이 발신 도메인 정렬 검사를 통과한다.|The supplier notification fails sender-domain alignment.|공급업체 알림이 발신 도메인 정렬 검사에 실패한다.|The notification concerns a shipment timetable.|알림은 배송 일정에 관한 것이다.
webhook_registration|Register the outbound notification destination.|외부 알림 목적지를 등록한다.|The notification destination is on the approved integration register.|알림 목적지가 승인된 연동 등록부에 있다.|The notification destination is absent from the approved integration register.|알림 목적지가 승인된 연동 등록부에 없다.|The notifications report batch completion times.|알림은 일괄 작업 완료 시간을 보고한다.
wireless_profile|Activate the conference wireless profile.|회의용 무선 프로필을 활성화한다.|The wireless profile uses the required authentication mode.|무선 프로필이 필수 인증 방식을 사용한다.|The wireless profile lacks the required authentication mode.|무선 프로필이 필수 인증 방식을 사용하지 않는다.|The profile is reserved for staff workshops.|프로필은 직원 워크숍용으로 지정되어 있다.
time_service|Use the proposed clock synchronization source.|제안된 시계 동기화 소스를 사용한다.|The clock source satisfies the approved time-authentication check.|시계 소스가 승인된 시간 인증 검사를 충족한다.|The clock source fails the approved time-authentication check.|시계 소스가 승인된 시간 인증 검사를 충족하지 못한다.|The source is proposed for the audit recorder.|소스는 감사 기록기를 위해 제안되었다.
change_window|Deploy the scheduled configuration change.|예정된 구성 변경을 배포한다.|The deployment falls within the approved change window.|배포가 승인된 변경 시간대 안에 있다.|The deployment falls outside the approved change window.|배포가 승인된 변경 시간대 밖에 있다.|The change updates the inventory dashboard layout.|변경은 자산 대시보드 배치를 갱신한다.
rollback_plan|Promote the service release to production.|서비스 릴리스를 운영 환경으로 승격한다.|The service release has a validated rollback plan.|서비스 릴리스에 검증된 복구 계획이 있다.|The service release lacks a validated rollback plan.|서비스 릴리스에 검증된 복구 계획이 없다.|The release updates the room-booking interface.|릴리스는 회의실 예약 화면을 갱신한다.
secret_rotation|Retire the previous application credential.|이전 애플리케이션 인증정보를 폐기한다.|All registered clients have migrated to the replacement credential.|등록된 모든 클라이언트가 대체 인증정보로 이전했다.|Some registered clients still depend on the previous credential.|등록된 일부 클라이언트가 여전히 이전 인증정보에 의존한다.|The credential belongs to the report delivery service.|인증정보는 보고서 전달 서비스에 속한다.
audit_continuity|Close the logging maintenance task.|로깅 유지보수 작업을 종료한다.|The event collector has restored continuous audit delivery.|이벤트 수집기가 연속적인 감사 자료 전달을 복구했다.|The event collector still has a gap in audit delivery.|이벤트 수집기의 감사 자료 전달에 여전히 공백이 있다.|The task covers the facilities scheduling application.|작업은 시설 일정 관리 애플리케이션을 다룬다.
incident_containment|Reconnect the isolated test host.|격리된 테스트 호스트를 다시 연결한다.|The isolated host passed the containment exit check.|격리된 호스트가 격리 해제 검사를 통과했다.|The isolated host failed the containment exit check.|격리된 호스트가 격리 해제 검사에 실패했다.|The host runs a disposable training exercise.|호스트는 일회용 교육 실습을 실행한다.
restore_capacity|Start the recovery migration.|복구 이전을 시작한다.|The recovery destination has the reserved capacity required by the plan.|복구 목적지에 계획상 필요한 용량이 예약되어 있다.|The recovery destination lacks the reserved capacity required by the plan.|복구 목적지에 계획상 필요한 용량이 예약되어 있지 않다.|The migration restores the public documentation mirror.|이전은 공개 문서 미러를 복구한다.
alert_suppression|Apply the maintenance alert suppression.|유지보수 경보 억제를 적용한다.|The suppression request has the required owner and expiry.|억제 요청에 필수 소유자와 만료 시점이 있다.|The suppression request lacks the required owner or expiry.|억제 요청에 필수 소유자 또는 만료 시점이 없다.|The alerts concern the synthetic availability probe.|경보는 합성 가용성 점검에 관한 것이다.
ticket_resolution|Resolve the security remediation ticket.|보안 개선 티켓을 완료 처리한다.|The remediation has passed the independent acceptance check.|개선 사항이 독립적인 인수 검사를 통과했다.|The remediation has failed the independent acceptance check.|개선 사항이 독립적인 인수 검사에 실패했다.|The ticket concerns access-log retention settings.|티켓은 접근 로그 보존 설정에 관한 것이다.
payment_approvers|Release the scheduled supplier payment.|예정된 공급업체 대금을 지급한다.|The payment has the required two independent approvals.|대금 지급에 필수적인 독립 승인 두 건이 있다.|The payment lacks the required two independent approvals.|대금 지급에 필수적인 독립 승인 두 건이 없다.|The payment covers replacement office equipment.|대금은 사무 장비 교체 비용이다.
bank_change|Accept the supplier bank-detail update.|공급업체 계좌 정보 변경을 접수한다.|The bank-detail update passed the independent callback check.|계좌 정보 변경이 독립적인 회신 전화 검사를 통과했다.|The bank-detail update failed the independent callback check.|계좌 정보 변경이 독립적인 회신 전화 검사에 실패했다.|The supplier provides meeting-room furniture.|공급업체는 회의실 가구를 제공한다.
refund_entitlement|Issue the requested subscription refund.|요청된 구독료 환불을 지급한다.|The subscription satisfies the documented refund entitlement.|구독이 문서화된 환불 자격을 충족한다.|The subscription does not satisfy the documented refund entitlement.|구독이 문서화된 환불 자격을 충족하지 못한다.|The subscription is for a team diagramming tool.|구독은 팀 다이어그램 도구용이다.
asset_disposal|Release the retired drive for recycling.|폐기된 드라이브를 재활용에 인도한다.|The retired drive has a complete sanitization record.|폐기된 드라이브에 완전한 데이터 삭제 기록이 있다.|The retired drive has an incomplete sanitization record.|폐기된 드라이브에 불완전한 데이터 삭제 기록이 있다.|The drive was used by a reception kiosk.|드라이브는 안내 키오스크에서 사용되었다.
shipment_custody|Accept the sealed evidence shipment.|봉인된 증거 배송물을 인수한다.|The shipment custody record has no unexplained transfer gap.|배송물 인계 기록에 설명되지 않은 이관 공백이 없다.|The shipment custody record has an unexplained transfer gap.|배송물 인계 기록에 설명되지 않은 이관 공백이 있다.|The shipment contains a retired badge reader.|배송물에는 폐기된 출입증 판독기가 들어 있다.
door_maintenance|Return the access-controlled door to service.|접근 통제 출입문을 다시 가동한다.|The door passed the fail-secure latch test.|출입문이 장애 시 잠금 유지 걸쇠 검사를 통과했다.|The door failed the fail-secure latch test.|출입문이 장애 시 잠금 유지 걸쇠 검사에 실패했다.|The door separates the archive room from reception.|출입문은 기록 보관실과 안내 공간을 구분한다.
camera_privacy|Enable the replacement security camera.|교체된 보안 카메라를 활성화한다.|The camera has the required privacy masking configuration.|카메라에 필수 사생활 보호 가림 설정이 적용되어 있다.|The camera lacks the required privacy masking configuration.|카메라에 필수 사생활 보호 가림 설정이 적용되어 있지 않다.|The camera observes the delivery entrance.|카메라는 배송 출입구를 관찰한다.
equipment_interlock|Return the laboratory cabinet to use.|연구실 보관함을 다시 사용한다.|The cabinet passed the required interlock inspection.|보관함이 필수 연동 잠금 검사를 통과했다.|The cabinet failed the required interlock inspection.|보관함이 필수 연동 잠금 검사에 실패했다.|The cabinet stores calibration reference devices.|보관함에는 교정 기준 장치가 보관되어 있다.
""".strip()


def catalog() -> list[dict]:
    fields = ("mechanism", "action_en", "action_ko", "positive_en", "positive_ko",
              "negative_en", "negative_ko", "context_en", "context_ko")
    rows = []
    for line in _ROWS.splitlines():
        values = line.split("|")
        if len(values) != len(fields):
            raise ValueError("invalid authored catalog row")
        rows.append(dict(zip(fields, values)))
    return rows
